# -*- coding: utf-8 -*-
"""Ciclo 01 - Resolução Exercicios 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1670lx1Wwpi5Po_Z9-A42JJGr9B77R8eW
"""

import numpy as np

10 + 300 + 0.4 + 10
np.sum( [10, 300, 0.4, 10] )

"""3. Desenvolva comandos em Python capaz de calcular a media harmonica entre 5 numeros. Por exemplo: 2,3,5,6,9"""

#2, 3, 5, 6, 9

x1 = int(input ('Digite o primeiro valor:'))
x2 =  int(input ('Digite o segundo valor:')) 
x3 = int(input ('Digite o terceiro valor:'))
x4 = int(input ('Digite o quarto valor:')) 
x5 = int(input ('Digite o quinto valor:'))

n = 5 

# media harmonica

#n / (1/2 + 1/3 + 1/5 + 1/6 + 1/9)

media_harmonica = n / (1/x1 + 1/x2 + 1/x3 + 1/x4 + 1/x5)

print( ' O valor da media harmonica he: {:.2f}'.format(media_harmonica))

"""4. Um cientista de Dados Jr precisa criar sequencia de comandos que seja capaz de calcular a media ponderada dos valores digitados pelo usuario. O usuario é capaz de digitar 8 valores. O primeiro numero tem peso 0.5, o segundo 1.0, p terceiro 1. 5 até o ultimo valor que tem peso 4, ou seja, os pesos sao acrescidos de 0.5 para cada valor. Portanto, o algaritimo deve ser capaz de calcular a media ponderada dos oito valores degitados pela usuario, cada valor com o seu respectivo peso."""

# 2,4, 5,8,2,5,7,7

x1 = 10 
x2 = 20
x3 = 8 
x4 = 5 
x5 = 4
x6 = 6 
x7 = 7
x8 = 2 


peso_01 = 0.5
peso_02 = 1.0
peso_03 = 1.5
peso_04 = 2.0
peso_05 = 2.5
peso_06 = 3.0 
peso_07 = 3.5
peso_08 = 4.0

#formula de media ponderada 
#(peso_01 * valor_01 ) + (peso_02 * valor_02 ) + (peso_03 * valor_03 ) + (peso_04 * valor_04 ) + (peso_05 * valor_05 ) + (peso_06 * valor_06 ) + (peso_07 * valor_07 ) + (peso_08 * valor_08 )

numerador = ((peso_01*x1) + (peso_02*x2) + (peso_03*x3) + (peso_04*x4) + (peso_05*x5) + (peso_06*x6) + (peso_07*x7) + (peso_08*x8))
denominador = (peso_01 + peso_02 + peso_03 + peso_04 + peso_05 + peso_06 + peso_07 + peso_08)

media_ponderada = numerador / denominador

print( 'O valor da media ponderada e: {}'.format(media_ponderada) )

"""1. Um programador Jr precisa construir uma mini calculadora. Essa calculadora segue os seguines padrões:

1. Se o usuario digitar um valor menor ou igual a 5, a calculadora vai multiplicar esse valor por 10 e retornar o valor resultantes para o usuario.

2. Se o usuario digitar um numero entre 6 e 10, a calculadora multiplica por 20 o numero digitado pelo usuario. 

3. Se o usuario digitar um valor maior ou igual a 11, a calculadora soma 100 ao numero digitado. Ajude o programador junior a construir essa calculadora, fornecendo os comandos em Python para ele.
"""

num = 20

if num < 5:
  resultado = num * 10
elif num <= 10:
  resultado = num + 20

else:
  resultado = num + 100

print( ' O valor e: {}'.format( resultado))

"""6. Um programador Jr precisa criar um algoritimo que consiga fazer a comparaçao entre três valores e exibir qual é o maior e qual é o menor valor digitado. Ajude o programador desenvolvendo o codigo em Python."""

num01 = 50
num02 = 2
num03 = 1

#descobrir qual e o maior valor
maior = num01
if num02 > maior:
   maior = num02

if num03 > maior:
  maior = num03   

#descobrir qual e é o menor valor
menor = num01

if num02 < menor:
  menor = num02

if num03 < menor:
  menor = num03  


print( ' O maior valor e: {}'.format(num01))
print( ' O menor valor e: {}'.format(num02))